# Generated by Django 5.2.8 on 2025-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_user_following_alter_follow_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_news_feed_visit",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
