# Generated by Django 5.2.8 on 2025-12-14 09:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_profile_last_news_feed_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
