"""Tests for static files (webpack build output)."""

from pathlib import Path

from django.conf import settings


class TestStaticFiles:
    """Tests for static files generated by webpack."""

    def test_compiled_js_exists(self):
        """Test that compiled JavaScript bundle exists."""
        # Files are now in frontend/dist (via STATICFILES_DIRS)
        # or in staticfiles after collectstatic
        static_dirs = settings.STATICFILES_DIRS
        if static_dirs:
            # Check STATICFILES_DIRS first (development)
            for static_dir in static_dirs:
                main_js = Path(static_dir) / "main.js"
                if main_js.exists():
                    assert main_js.is_file()
                    assert main_js.stat().st_size > 0
                    return

        # Fallback: check STATIC_ROOT (production after collectstatic)
        static_root = Path(
            settings.STATIC_ROOT or settings.BASE_DIR / "staticfiles"
        )
        main_js = static_root / "main.js"
        if main_js.exists():
            assert main_js.is_file()
            assert main_js.stat().st_size > 0

    def test_compiled_css_exists(self):
        """Test that compiled CSS file exists."""
        # Files are now in frontend/dist (via STATICFILES_DIRS)
        # or in staticfiles after collectstatic
        static_dirs = settings.STATICFILES_DIRS
        if static_dirs:
            # Check STATICFILES_DIRS first (development)
            for static_dir in static_dirs:
                styles_css = Path(static_dir) / "styles.css"
                if styles_css.exists():
                    assert styles_css.is_file()
                    assert styles_css.stat().st_size > 0
                    return

        # Fallback: check STATIC_ROOT (production after collectstatic)
        static_root = Path(
            settings.STATIC_ROOT or settings.BASE_DIR / "staticfiles"
        )
        styles_css = static_root / "styles.css"
        if styles_css.exists():
            assert styles_css.is_file()
            assert styles_css.stat().st_size > 0

    def test_static_files_served(self, client):
        """Test that static files are served correctly."""
        # This test checks if static files can be accessed
        # In production, static files should be served by WhiteNoise or web server
        # Files are now in frontend/dist, so URL is /static/main.js (not /static/dist/main.js)
        response = client.get("/static/main.js", follow=True)
        # May return 404 if files not built, or 200 if served
        assert response.status_code in [200, 404]

    def test_static_css_served(self, client):
        """Test that CSS static files are served correctly."""
        # Files are now in frontend/dist, so URL is /static/styles.css (not /static/dist/styles.css)
        response = client.get("/static/styles.css", follow=True)
        # May return 404 if files not built, or 200 if served
        assert response.status_code in [200, 404]
